import os

os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 20")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 20 -sgo")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo test__.graph")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 20 -sgo 17")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo test__.graph 17")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 -sgo -vlc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 0.3 -sgo -vlc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 -sgo -elc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 0.3 -sgo -elc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 -sgo -vlc -elc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 10 0.6 -sgo -vlc -elc")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo -vlc "
          "custom_vertex_label_test.py e_is_c ")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo -elc "
          "custom_edge_label_test.py a_is_b")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo -vlc "
          "custom_vertex_label_test.py e_is_c -elc custom_edge_label_test.py a_is_b")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 60 0.3 -sgo")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 20 -sgo -nsi")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb -sgo -gt pairwise_align -no test.newick")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 5 -sgo")
print("\n")
os.system("pypy3 GraphDating.py -i gross.graph mittel.graph klein.graph -ga mb 5 -sgo -nh")
print("\n")
os.system("pypy3 GraphDating.py -i Ethanol.json Methane.json -if json -ga bk 30 -sgo -nsi -vlc")
print("\n")
os.system("pypy3 GraphDating.py -i Ethane.json Methane.json -if json -ga bk 30 -sgo -cc -nsi -vlc")
